Update reproducible-builds.yml
Cleanup

diff --git a/.github/workflows/reproducible-builds.yml b/.github/workflows/reproducible-builds.yml
--- a/.github/workflows/reproducible-builds.yml
+++ b/.github/workflows/reproducible-builds.yml
@@ -46,31 +46,29 @@ jobs:
         cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null
         sudo apt-get update
 
-    # Note: For beta versions, the APT version is separated by tilde ~ e.g. v1.2.3~beta.1
-    # However the download URI contains dashes e.g. v1.2.3-beta.1
-    # Thus after apt-get download we need to check the filename of the actual download
+    # Note: For beta versions, the APT version is separated by tilde e.g. v1.2.3~beta.1
+    # However the download URI has a dash e.g. v1.2.3-beta.1
+    # Thus after apt-get download we need to use the filename of the actual download
     - name: Download latest deb
       id: download
       run: |
         DOWNLOAD_URI=$(apt-get download --print-uris "$PACKAGE_NAME=$PACKAGE_VERSION" | cut -d"'" -f2)
         EXPECTED_SHA512=$(apt-get download --print-uris "$PACKAGE_NAME=$PACKAGE_VERSION" | grep -oP 'SHA512:\K\s*\S+')
+        echo "expected_sha512=$EXPECTED_SHA512" >> $GITHUB_OUTPUT
 
         apt-get download "$PACKAGE_NAME=$PACKAGE_VERSION"
         DEB_FILE=$(ls | grep deb | tail -1)
-        DOWNLOAD_SHA512=$(sha512sum $DEB_FILE | cut -d' ' -f1)
-        if [ "$DOWNLOAD_SHA512" == "$EXPECTED_SHA512" ]; then
-          echo "Download SHA512 checksum verification successful for $DEB_FILE"
-        else
-          echo "Download SHA512 checksum verification failed!"
-          echo "Expected: $EXPECTED_SHA512"
-          echo "Actual:   $DOWNLOAD_SHA512"
-          exit 1
-        fi
-
         echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT
 
+        DOWNLOAD_SHA512=$(sha512sum $DEB_FILE | cut -d' ' -f1)
         echo "Expected SHA512: $EXPECTED_SHA512"
-        echo "expected_sha512=$EXPECTED_SHA512" >> $GITHUB_OUTPUT
+        echo "Actual SHA512:   $DOWNLOAD_SHA512"
+        if [ "$DOWNLOAD_SHA512" == "$EXPECTED_SHA512" ]; then
+          echo "Download checksum verification successful for $DEB_FILE"
+        else
+          echo "Download checksum verification failed!"
+          exit 1
+        fi
 
     - name: Clone Desktop git repo
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
@@ -116,11 +114,11 @@ jobs:
       run: |
         ACTUAL_SHA512="${{ steps.build.outputs.actual_sha512 }}"
         EXPECTED_SHA512="${{ steps.download.outputs.expected_sha512 }}"
+        echo "Expected SHA512: $EXPECTED_SHA512"
+        echo "Actual SHA512:   $ACTUAL_SHA512"
         if [ "$ACTUAL_SHA512" == "$EXPECTED_SHA512" ]; then
-          echo "✅ SHA512 Checksum verification successful for ${{ steps.download.outputs.deb_file }}"
+          echo "✅ Checksum verification successful for ${{ steps.download.outputs.deb_file }}"
         else
-          echo "❌ SHA512 Checksum verification failed!"
-          echo "Expected: $EXPECTED_SHA512"
-          echo "Actual:   $ACTUAL_SHA512"
+          echo "❌ Checksum verification failed!"
           exit 1
         fi
