Update reproducible-builds.yml
update for beta tilde versions

diff --git a/.github/workflows/reproducible-builds.yml b/.github/workflows/reproducible-builds.yml
--- a/.github/workflows/reproducible-builds.yml
+++ b/.github/workflows/reproducible-builds.yml
@@ -45,18 +45,32 @@ jobs:
         wget -O signal-desktop.sources https://updates.signal.org/static/desktop/apt/signal-desktop.sources
         cat signal-desktop.sources | sudo tee /etc/apt/sources.list.d/signal-desktop.sources > /dev/null
         sudo apt-get update
+
+    # Note: For beta versions, the APT version is separated by tilde ~ e.g. v1.2.3~beta.1
+    # However the download URI contains dashes e.g. v1.2.3-beta.1
+    # Thus after apt-get download we need to check the filename of the actual download
     - name: Download latest deb
       id: download
       run: |
         DOWNLOAD_URI=$(apt-get download --print-uris "$PACKAGE_NAME=$PACKAGE_VERSION" | cut -d"'" -f2)
-        DEB_FILE=$(basename "$DOWNLOAD_URI")
-        echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT
+        EXPECTED_SHA512=$(apt-get download --print-uris "$PACKAGE_NAME=$PACKAGE_VERSION" | grep -oP 'SHA512:\K\s*\S+')
 
         apt-get download "$PACKAGE_NAME=$PACKAGE_VERSION"
+        DEB_FILE=$(ls | grep deb | tail -1)
+        DOWNLOAD_SHA512=$(sha512sum $DEB_FILE | cut -d' ' -f1)
+        if [ "$DOWNLOAD_SHA512" != "$EXPECTED_SHA512" ]; then
+          echo "Download SHA512 checksum verification successful for $DEB_FILE"
+        else
+          echo "Download SHA512 checksum verification failed!"
+          echo "Expected: $EXPECTED_SHA512"
+          echo "Actual:   $DOWNLOAD_SHA512"
+          exit 1
+        fi
 
-        EXPECTED_SHA256=$(sha256sum "$DEB_FILE" | cut -d' ' -f1)
-        echo "Expected SHA256: $EXPECTED_SHA256"
-        echo "expected_sha256=$EXPECTED_SHA256" >> $GITHUB_OUTPUT
+        echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT
+
+        echo "Expected SHA512: $EXPECTED_SHA512"
+        echo "expected_sha512=$EXPECTED_SHA512" >> $GITHUB_OUTPUT
 
     - name: Clone Desktop git repo
       uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
@@ -93,20 +107,20 @@ jobs:
 
         cd ../release
         BUILT_FILE=$(ls | grep deb | tail -1)
-        ACTUAL_SHA256=$(sha256sum $BUILT_FILE | cut -d' ' -f1)
-        echo "actual_sha256=$ACTUAL_SHA256" >> $GITHUB_OUTPUT
+        ACTUAL_SHA512=$(sha512sum $BUILT_FILE | cut -d' ' -f1)
+        echo "actual_sha512=$ACTUAL_SHA512" >> $GITHUB_OUTPUT
       env:
         SKIP_DOCKER_BUILD: true
 
     - name: Compare checksums
       run: |
-        ACTUAL_SHA256="${{ steps.build.outputs.actual_sha256 }}"
-        EXPECTED_SHA256="${{ steps.download.outputs.expected_sha256 }}"
-        if [ "$ACTUAL_SHA256" == "$EXPECTED_SHA256" ]; then
-          echo "✅ Checksum verification successful for ${{ steps.download.outputs.deb_file }}"
+        ACTUAL_SHA512="${{ steps.build.outputs.actual_sha512 }}"
+        EXPECTED_SHA512="${{ steps.download.outputs.expected_sha512 }}"
+        if [ "$ACTUAL_SHA512" == "$EXPECTED_SHA512" ]; then
+          echo "✅ SHA512 Checksum verification successful for ${{ steps.download.outputs.deb_file }}"
         else
-          echo "❌ Checksum verification failed!"
-          echo "Expected: $EXPECTED_SHA256"
-          echo "Actual:   $ACTUAL_SHA256"
+          echo "❌ SHA512 Checksum verification failed!"
+          echo "Expected: $EXPECTED_SHA512"
+          echo "Actual:   $ACTUAL_SHA512"
           exit 1
         fi
